import type { Metadata } from "next";
import "./globals.css";
import AuthProvider from "./Providers";
import { ToastContainer } from "react-toastify";

export const metadata: Metadata = {
  title: "RBAC-CRUD",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-amber-50">
        <AuthProvider>{children}</AuthProvider>
        <ToastContainer />
      </body>
    </html>
  );
}
